---
title: "Preparing PRCA data for prediction of type of sample (cancer or healthy)"
output: html_notebook
---

```{r}
AddSurvDataToOmics <- function(diseases, omics, save = FALSE){
  for(dis in diseases){
    # preparing clinical data
    # if(!exists("clin")){#}, where = .GlobalEnv)){
    print(dis)
    if(exists(sprintf("%s.%s.20160128", dis, "clinical"))){
      clin <<- get(sprintf("%s.%s.20160128", dis, "clinical"), envir = .GlobalEnv)
      print(sprintf("For %s, clinical data from 2016-01-28 will be used", dis))
    }
    else{
      clin <<- get(sprintf("%s.%s", dis, "clinical"), envir = .GlobalEnv)
      print(sprintf("Clinical data from 2016-01-28 is not available, will use old data for %s.", dis))
    }
    patients_clin <<- toupper(clin$patient.bcr_patient_barcode)
    rownames(clin) <<- patients_clin
    for(om in omics){
      print(om)
      string <- sprintf("%s.%s.20160128", dis, om)
      if(exists(string)){
        df <- get(string)
      }
      else {
        string <- sprintf("%s.%s", dis, om)
        if(exists(string)){
          df <- get(string)
        }
        else{next}
      }
      dis_om <- sprintf("%s_%s", dis, om)
      if(om == "CNV"){
        assign(dis_om, AddSurvivalData(df, clin, om), envir = .GlobalEnv)
      }
      else{
        if(rownames(df)[1] == 1){
          rownames(df) <- toupper(df$bcr_patient_barcode)
        }
        assign(dis_om, AddSurvivalData(df, clin, om), envir = .GlobalEnv)
      }
      if(save){
        writeFile(get(dis_om), dis_om)
      }
    }
  }
}
```
```{r}
test <- AddSurvDataToOmics("PRAD", "mRNA")
```

